refactor: adjust formatting

diff --git a/bin/git-bare-clone b/bin/git-bare-clone
--- a/bin/git-bare-clone
+++ b/bin/git-bare-clone
@@ -4,7 +4,7 @@ set -Eeuo pipefail
 trap cleanup SIGINT SIGTERM ERR EXIT
 
 usage() {
-  cat << EOF # remove the space between << and EOF, this is due to web plugin issue
+	cat << EOF # remove the space between << and EOF, this is due to web plugin issue
 Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-l] repository
 
 Clone a bare git repo and set up environment for working comfortably and exclusively from worktrees.
@@ -15,57 +15,57 @@ Available options:
 -v, --verbose   Print script debug info
 -l, --location  Location of the bare repo contents (default: .bare)
 EOF
-  exit
+	exit
 }
 
 cleanup() {
-  trap - SIGINT SIGTERM ERR EXIT
+	trap - SIGINT SIGTERM ERR EXIT
 }
 
 setup_colors() {
-  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
-  else
-    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
-  fi
+	if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+		NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+	else
+		NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+	fi
 }
 
 msg() {
-  echo >&2 -e "${1-}"
+	echo >&2 -e "${1-}"
 }
 
 die() {
-  local msg=$1
-  local code=${2-1} # default exit status 1
-  msg "$msg"
-  exit "$code"
+	local msg=$1
+	local code=${2-1} # default exit status 1
+	msg "$msg"
+	exit "$code"
 }
 
 parse_params() {
-  location='.bare'
+	location='.bare'
 
-  while :; do
-    case "${1-}" in
-    -h | --help) usage ;;
-    -v | --verbose) set -x ;;
-    --no-color) NO_COLOR=1 ;;
-    -l | --location)
-        location="${2-}" 
-        shift
-        ;;
-    -?*) die "Unknown option: $1" ;;
-    *) break ;;
-    esac
-    shift
-  done
+	while :; do
+		case "${1-}" in
+		-h | --help) usage ;;
+		-v | --verbose) set -x ;;
+		--no-color) NO_COLOR=1 ;;
+		-l | --location)
+				location="${2-}" 
+				shift
+				;;
+		-?*) die "Unknown option: $1" ;;
+		*) break ;;
+		esac
+		shift
+	done
 
-  args=("$@")
+	args=("$@")
 
-  # check required params and arguments
-  # [[ -z "${param-}" ]] && die "Missing required parameter: param"
-  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+	# check required params and arguments
+	# [[ -z "${param-}" ]] && die "Missing required parameter: param"
+	[[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
 
-  return 0
+	return 0
 }
 
 parse_params "$@"
diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -4,11 +4,11 @@ set -Eeuo pipefail
 trap cleanup SIGINT SIGTERM ERR EXIT
 
 cleanup() {
-  trap - SIGINT SIGTERM ERR EXIT
+	trap - SIGINT SIGTERM ERR EXIT
 }
 
 usage() {
-  cat << EOF # remove the space between << and EOF, this is due to web plugin issue
+	cat << EOF # remove the space between << and EOF, this is due to web plugin issue
 Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-c] path/to/file.spec.ts
 
 Simplify running targeted tests and gathering coverage data.
@@ -26,57 +26,57 @@ Available options:
 -w, --watch     Enable Jest's watcher
 -j, --jest      Use Jest to run the tests instead of react-scripts
 EOF
-  exit
+	exit
 }
 
 setup_colors() {
-  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
-  else
-    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
-  fi
+	if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+		NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+	else
+		NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+	fi
 }
 
 msg() {
-  echo >&2 -e "${1-}"
+	echo >&2 -e "${1-}"
 }
 
 die() {
-  local msg=$1
-  local code=${2-1} # default exit status 1
-  msg "$msg"
-  exit "$code"
+	local msg=$1
+	local code=${2-1} # default exit status 1
+	msg "$msg"
+	exit "$code"
 }
 
 parse_params() {
-  collect_coverage=0
-  watch_flags="--watch=false --watchAll=false"
-  command="react-scripts test"
+	collect_coverage=0
+	watch_flags="--watch=false --watchAll=false"
+	command="react-scripts test"
 
-  while :; do
-    case "${1-}" in
-    -h | --help) usage ;;
-    -v | --verbose) set -x ;;
-    --no-color) NO_COLOR=1 ;;
-    -w | --watch) watch_flags="--watch=true" ;;
-    -j | --jest) command="jest" ;;
-    -c | --coverage)
-        collect_coverage=1
-        ;;
-    -?*) die "Unknown option: $1" ;;
-    *) break ;;
-    esac
-    shift
-  done
+	while :; do
+		case "${1-}" in
+		-h | --help) usage ;;
+		-v | --verbose) set -x ;;
+		--no-color) NO_COLOR=1 ;;
+		-w | --watch) watch_flags="--watch=true" ;;
+		-j | --jest) command="jest" ;;
+		-c | --coverage)
+				collect_coverage=1
+				;;
+		-?*) die "Unknown option: $1" ;;
+		*) break ;;
+		esac
+		shift
+	done
 
-  args=("$@")
+	args=("$@")
 
-  # check required params and arguments
-  # [[ -z "${param-}" ]] && die "Missing required parameter: param"
-  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
-  spec_file=${args[0]}
+	# check required params and arguments
+	# [[ -z "${param-}" ]] && die "Missing required parameter: param"
+	[[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+	spec_file=${args[0]}
 
-  return 0
+	return 0
 }
 
 parse_params "$@"
@@ -84,10 +84,10 @@ setup_colors
 
 coverage_file=""
 if [[ $collect_coverage -eq 1 ]]; then
-  coverage_file=${spec_file//\.spec/}
-  coverage_flags="--coverage=true --collectCoverageFrom=\"$coverage_file\""
+	coverage_file=${spec_file//\.spec/}
+	coverage_flags="--coverage=true --collectCoverageFrom=\"$coverage_file\""
 else
-  coverage_flags="--coverage=false"
+	coverage_flags="--coverage=false"
 fi
 
 npx $command --color $watch_flags $coverage_flags "$spec_file"
