chore: update openai script

diff --git a/bin/openai b/bin/openai
--- a/bin/openai
+++ b/bin/openai
@@ -1,35 +1,45 @@
 #!/usr/bin/env bash
 #
-# OpenAI CLI v2.2.2
+# OpenAI CLI v3.0
 #   Created by @janlay
 #
 
 set -eo pipefail
 
-# openai-cli accepts various exported environment variables:
-#   OPENAI_API_KEY		: OpenAI's API key
-#   OPENAI_API_ENDPOINT	: Custom API endpoint
-#   OPENAI_MAX_TOKENS   : Maximum number of tokens to use
-#	OPENAI_CHAT_MODEL	: ChatGPT model
-#   OPENAI_DATA_DIR		: Directory to store data
-OPENAI_API_ENDPOINT="${OPENAI_API_ENDPOINT:-https://api.openai.com}"
-OPENAI_API_KEY="${OPENAI_API_KEY:-}"
-OPENAI_MAX_TOKENS="${OPENAI_MAX_TOKENS:-2000}"
-OPENAI_CHAT_MODEL="${OPENAI_CHAT_MODEL:-gpt-3.5-turbo-1106}"
 declare _config_dir="${OPENAI_DATA_DIR:-$XDG_CONFIG_HOME}"
 OPENAI_DATA_DIR="${_config_dir:-$HOME/.openai}"
 
+# Read config file?
+[ -e "$OPENAI_DATA_DIR"/config ] && . "$OPENAI_DATA_DIR"/config
+
+# openai-cli accepts various exported environment variables:
+#   OPENAI_API_KEY		: OpenAI's API key
+#   OPENAI_API_ENDPOINT	: Custom API endpoint
+#	OPENAI_API_MODEL	: Which model to use
+#   OPENAI_DATA_DIR		: Directory to store data
+OPENAI_API_ENDPOINT="${OPENAI_API_ENDPOINT:-https://api.openai.com/v1}"
+OPENAI_API_KEY="${OPENAI_API_KEY:-}"
+OPENAI_API_MODEL="${OPENAI_API_MODEL:-gpt-4o}"
+
 # defaults
-readonly _app_name=openai _app_version=2.2.2
-readonly default_api_version=1 default_api_name=chat/completions default_model="$OPENAI_CHAT_MODEL" default_topic=General
+readonly _app_name=openai _app_version=3.0
+readonly provider="${OPENAI_COMPATIBLE_PROVIDER:-OPENAI}"
+readonly default_api_name=chat/completions default_model="$OPENAI_API_MODEL" default_topic=General
 
 declare -i chat_mode=0 dry_run=0
-declare tokens_file="$OPENAI_DATA_DIR/total_tokens" api_version=$default_api_version api_name=$default_api_name topic=$default_topic
+declare tokens_file="$OPENAI_DATA_DIR/total_tokens" api_name=$default_api_name topic=$default_topic
 declare dump_file dumped_file data_file temp_dir rest_args prompt_file prompt
 
 trap cleanup EXIT
 cleanup() {
-	[ -d "$temp_dir" ] || rm -f -- "$temp_dir"
+	if [ -d "$temp_dir" ]; then
+		rm -rf -- "$temp_dir"
+	fi
+}
+
+get_env() {
+	local env_key="${provider}_${1}"
+	echo "${!env_key}"
 }
 
 raise_error() {
@@ -142,8 +152,15 @@ openai_embeddings() {
 }
 
 openai_chat_completions() {
-	[ -n "$dumped_file" ] || {
-		local prop_file="$temp_dir/props" payload="{\"model\": \"$default_model\", \"stream\": true, \"temperature\": 0.5, \"max_tokens\": $OPENAI_MAX_TOKENS}"
+	local streaming=0
+	if [ -n "$dumped_file" ]; then
+		# only succeeds when the dumped file is not streamed
+		jq -er '.choices[0].message.content' <"$dumped_file" 2>/dev/null && return
+		streaming=1
+	else
+		local prop_file="$temp_dir/props" model payload
+		model=$(get_env API_MODEL)
+		payload="{\"model\": \"$model\", \"stream\": true}"
 
 		# overwrite default properties with user's
 		read_prompt
@@ -166,43 +183,53 @@ openai_chat_completions() {
 		local payload_file="$temp_dir/payload" input_file="$temp_dir/prompt"
 		[ -f "$input_file" ] || input_file="${prompt_file:-/dev/stdin}"
 		jq -Rs -cn --argjson payload "$payload" '$payload | .messages += [{role: "user", content: input}]' "$input_file" >"$payload_file"
-	}
+
+		streaming=$(jq -e 'if .stream then 1 else 0 end' <"$payload_file")
+
+		# check o1's parameters
+		jq -e 'select(.model | test("^o\\d")) and (.temperature or .top_p or .presence_penalty or .frequency_penalty .logprobs or .top_logprobs .logit_bias)' <"$payload_file" &>/dev/null && raise_error 'One or more unsupported API parameters used for model o1. See https://platform.openai.com/docs/guides/reasoning#limitations for more details.' 5
+	fi
 
 	local chunk reason text role fn_name
-	call_api | while read -r chunk; do
-		[ -z "$chunk" ] && continue
-		chunk=$(cut -d: -f2- <<<"$chunk" | jq '.choices[0]')
-		reason=$(jq -r '.finish_reason // empty' <<<"$chunk")
-		[[ $reason = stop || $reason = function_call ]] && break
-		[ -n "$reason" ] && raise_error "API error: $reason" 10
+	if [ $streaming -eq 1 ]; then
+		call_api | while read -r chunk; do
+			[ -z "$chunk" ] && continue
+			chunk=$(cut -d: -f2- <<<"$chunk" | jq '.choices[0]')
+			reason=$(jq -r '.finish_reason // empty' <<<"$chunk")
+			[[ $reason = stop || $reason = function_call ]] && break
+			[ -n "$reason" ] && raise_error "API error: $reason" 10
 
-		# get role and function info from the first chunk
-		[ -z "$role" ] && {
-			role=$(jq -r '.delta.role // empty' <<<"$chunk")
-			fn_name=$(jq -r '.delta.function_call.name // empty' <<<"$chunk")
-		}
+			# get role and function info from the first chunk
+			[ -z "$role" ] && {
+				role=$(jq -r '.delta.role // empty' <<<"$chunk")
+				fn_name=$(jq -r '.delta.function_call.name // empty' <<<"$chunk")
+			}
 
-		# workaround: https://stackoverflow.com/a/15184414
-		chunk=$(
-			jq -r '.delta | .function_call.arguments // .content // empty' <<<"$chunk"
-			printf x
-		)
-		# ensure chunk is not empty
-		[ ${#chunk} -ge 2 ] || continue
+			# workaround: https://stackoverflow.com/a/15184414
+			chunk=$(
+				jq -r '.delta | .function_call.arguments // .content // empty' <<<"$chunk"
+				printf x
+			)
+			# ensure chunk is not empty
+			[ ${#chunk} -ge 2 ] || continue
 
-		chunk="${chunk:0:${#chunk}-2}"
-		text="$text$chunk"
-		echo -n "$chunk"
-	done
+			chunk="${chunk:0:${#chunk}-2}"
+			text="$text$chunk"
+			echo -n "$chunk"
+		done
+		[ "$dry_run" -eq 0 ] && echo
+	else
+		text=$(call_api | jq -er '.choices[0].message.content')
+		echo "$text"
+	fi
 
 	# append response to topic file for chat mode
-	[ "$chat_mode" -eq 1 ] && {
+	if [ "$chat_mode" -eq 1 ]; then
 		[ -n "$fn_name" ] && text=$(jq -n --arg name "$fn_name" --argjson arguments "${text:-\{\}}" '{function_call: {$name, $arguments}}')
 
 		update_conversation user "$prompt"
 		update_conversation "$role" "$text"
-	}
-	echo
+	fi
 }
 
 # shellcheck disable=SC2120
@@ -213,7 +240,7 @@ call_api() {
 		return
 	}
 
-	local url="$OPENAI_API_ENDPOINT/v$api_version/$api_name" auth="Bearer $OPENAI_API_KEY"
+	local url="$(get_env API_ENDPOINT)/$api_name" auth="Bearer $(get_env API_KEY)"
 
 	# dry-run mode
 	[ "$dry_run" -eq 1 ] && {
@@ -247,10 +274,10 @@ usage() {
 
 SYNOPSIS
   ABSTRACT
-    $_app_name [-n] [-a api_name] [-v api_version] [-o dump_file] [INPUT...]
-	$_app_name -i dumped_file
+    $_app_name [-n] [-a api_name] [-o dump_file] [INPUT...]
+    $_app_name -i dumped_file
 
-  DEFAULT_API (v$default_api_version/$default_api_name)
+  DEFAULT_API ($default_api_name)
     $_app_name [-c] [+property=value...] [@TOPIC] [-f file | prompt ...]
 	prompt
 			Prompt string for the request to OpenAI API. This can consist of multiple
@@ -263,18 +290,16 @@ SYNOPSIS
 	property=value
 			Overwrites default properties in payload. Prepend a plus sign '+' before property=value.
 			eg: +model=gpt-3.5-turbo-0301, +stream=false
-	
+
 	TOPICS
 			Topic starts with an at sign '@'.
 			To create new topic, use \`$_app_name @new_topic initial prompt'
-  
+
   OTHER APIS
     $_app_name -a models
 
 GLOBAL OPTIONS
   Global options apply to all APIs.
-  -v version
-		API version, default is '$default_api_version'.
   -a name
 		API name, default is '$default_api_name'.
   -n
@@ -298,9 +323,6 @@ parse() {
 		case "$opt" in
 		c)
 			chat_mode=1
-			;;
-		v)
-			api_version="$OPTARG"
 			;;
 		a)
 			api_name="$OPTARG"
@@ -343,6 +365,17 @@ check_bin() {
 }
 
 main() {
+	# show compatible provider if applicable
+	if [ "${SUPPRESS_PROVIDER_TIPS:-0}" -eq 0 ] && [ -n "$OPENAI_COMPATIBLE_PROVIDER" ]; then
+		echo "OpenAI compatible provider: $OPENAI_COMPATIBLE_PROVIDER" >&2
+	fi
+
+	# check required config
+	local key
+	for key in API_ENDPOINT API_KEY API_MODEL; do
+		[ -z "$(get_env "$key")" ] && raise_error "Missing environment variable: ${provider}_$key." 1
+	done
+
 	parse "$@"
 	check_bin jq 10
 
@@ -351,8 +384,6 @@ main() {
 	temp_dir=$(mktemp -d)
 
 	if [[ $topic == "$default_topic" || -f "$data_file" ]]; then
-		[ -z "$OPENAI_API_KEY" ] && raise_error 'OpenAI API key is required.' 11
-
 		local fn="openai_${api_name//\//_}"
 		[ "$(type -t "$fn")" = function ] || raise_error "API '$api_name' is not available." 12
 		"$fn"
